### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ccraddock** [Brainhack-Proceedings-2015/Keshavan_HBM_BrainShapeVis#3]
This is a well written report about a project to create a visualization app for Mindboggle results. A great feature of this tool, that is under-described in the report, is the region specific plots of shape measures. I encourage the authors to provide a little more about this and to add a figure showing it off.

**Comment by bcipolli** [comment]
@akeshavan Is this something you'd have time to help out with too?

**Comment by akeshavan** [comment]
@bcipolli Sure!
